/*
 * Snippet
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BodyLoginAuthLoginPost model module.
 * @module model/BodyLoginAuthLoginPost
 * @version 0.1.0
 */
export class BodyLoginAuthLoginPost {
  /**
   * Constructs a new <code>BodyLoginAuthLoginPost</code>.
   * @alias module:model/BodyLoginAuthLoginPost
   * @class
   * @param username {String} 
   * @param password {String} 
   */
  constructor(username, password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>BodyLoginAuthLoginPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BodyLoginAuthLoginPost} obj Optional instance to populate.
   * @return {module:model/BodyLoginAuthLoginPost} The populated <code>BodyLoginAuthLoginPost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BodyLoginAuthLoginPost();
      if (data.hasOwnProperty('grant_type'))
        obj.grantType = ApiClient.convertToType(data['grant_type'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('scope'))
        obj.scope = ApiClient.convertToType(data['scope'], 'String');
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
      if (data.hasOwnProperty('client_secret'))
        obj.clientSecret = ApiClient.convertToType(data['client_secret'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} grantType
 */
BodyLoginAuthLoginPost.prototype.grantType = undefined;

/**
 * @member {String} username
 */
BodyLoginAuthLoginPost.prototype.username = undefined;

/**
 * @member {String} password
 */
BodyLoginAuthLoginPost.prototype.password = undefined;

/**
 * @member {String} scope
 * @default ''
 */
BodyLoginAuthLoginPost.prototype.scope = '';

/**
 * @member {String} clientId
 */
BodyLoginAuthLoginPost.prototype.clientId = undefined;

/**
 * @member {String} clientSecret
 */
BodyLoginAuthLoginPost.prototype.clientSecret = undefined;

