/*
 * Snippet
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MessageSendForm model module.
 * @module model/MessageSendForm
 * @version 0.1.0
 */
export class MessageSendForm {
  /**
   * Constructs a new <code>MessageSendForm</code>.
   * @alias module:model/MessageSendForm
   * @class
   * @param message {String} 
   */
  constructor(message) {
    this.message = message;
  }

  /**
   * Constructs a <code>MessageSendForm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageSendForm} obj Optional instance to populate.
   * @return {module:model/MessageSendForm} The populated <code>MessageSendForm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageSendForm();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
MessageSendForm.prototype.message = undefined;

