/*
 * Snippet
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RegistrationForm model module.
 * @module model/RegistrationForm
 * @version 0.1.0
 */
export class RegistrationForm {
  /**
   * Constructs a new <code>RegistrationForm</code>.
   * @alias module:model/RegistrationForm
   * @class
   * @param username {String} 
   * @param email {String} 
   * @param password {String} 
   */
  constructor(username, email, password) {
    this.username = username;
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>RegistrationForm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegistrationForm} obj Optional instance to populate.
   * @return {module:model/RegistrationForm} The populated <code>RegistrationForm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegistrationForm();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
RegistrationForm.prototype.username = undefined;

/**
 * @member {String} email
 */
RegistrationForm.prototype.email = undefined;

/**
 * @member {String} password
 */
RegistrationForm.prototype.password = undefined;

