/*
 * Snippet
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Snippet);
  }
}(this, function(expect, Snippet) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MessageResponseForm', function() {
      beforeEach(function() {
        instance = new Snippet.MessageResponseForm();
      });

      it('should create an instance of MessageResponseForm', function() {
        // TODO: update the code to test MessageResponseForm
        expect(instance).to.be.a(Snippet.MessageResponseForm);
      });

      it('should have the property respondingToId (base name: "responding_to_id")', function() {
        // TODO: update the code to test the property respondingToId
        expect(instance).to.have.property('respondingToId');
        // expect(instance.respondingToId).to.be(expectedValueLiteral);
      });

      it('should have the property response (base name: "response")', function() {
        // TODO: update the code to test the property response
        expect(instance).to.have.property('response');
        // expect(instance.response).to.be(expectedValueLiteral);
      });

    });
  });

}));
