/*
 * Snippet
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AnyOfValidationErrorLocItems} from './model/AnyOfValidationErrorLocItems';
import {BodyLoginAuthLoginPost} from './model/BodyLoginAuthLoginPost';
import {HTTPValidationError} from './model/HTTPValidationError';
import {Message} from './model/Message';
import {MessageResponseForm} from './model/MessageResponseForm';
import {MessageSendForm} from './model/MessageSendForm';
import {PasswordChangeForm} from './model/PasswordChangeForm';
import {PasswordChangeRequest} from './model/PasswordChangeRequest';
import {RegistrationForm} from './model/RegistrationForm';
import {ValidationError} from './model/ValidationError';
import {AuthApi} from './api/AuthApi';
import {BottlesApi} from './api/BottlesApi';
import {HomeApi} from './api/HomeApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Snippet = require('index'); // See note below*.
* var xxxSvc = new Snippet.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Snippet.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Snippet.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Snippet.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnyOfValidationErrorLocItems model constructor.
     * @property {module:model/AnyOfValidationErrorLocItems}
     */
    AnyOfValidationErrorLocItems,

    /**
     * The BodyLoginAuthLoginPost model constructor.
     * @property {module:model/BodyLoginAuthLoginPost}
     */
    BodyLoginAuthLoginPost,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageResponseForm model constructor.
     * @property {module:model/MessageResponseForm}
     */
    MessageResponseForm,

    /**
     * The MessageSendForm model constructor.
     * @property {module:model/MessageSendForm}
     */
    MessageSendForm,

    /**
     * The PasswordChangeForm model constructor.
     * @property {module:model/PasswordChangeForm}
     */
    PasswordChangeForm,

    /**
     * The PasswordChangeRequest model constructor.
     * @property {module:model/PasswordChangeRequest}
     */
    PasswordChangeRequest,

    /**
     * The RegistrationForm model constructor.
     * @property {module:model/RegistrationForm}
     */
    RegistrationForm,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BottlesApi service constructor.
    * @property {module:api/BottlesApi}
    */
    BottlesApi,

    /**
    * The HomeApi service constructor.
    * @property {module:api/HomeApi}
    */
    HomeApi
};
